'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Components
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("myLocalization.Components", GetType(Components).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Test.
        '''</summary>
        Public Shared ReadOnly Property btnTest() As String
            Get
                Return ResourceManager.GetString("btnTest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark.
        '''</summary>
        Public Shared ReadOnly Property mnuCDark() As String
            Get
                Return ResourceManager.GetString("mnuCDark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change-lot number.
        '''</summary>
        Public Shared ReadOnly Property mnuChangeLN() As String
            Get
                Return ResourceManager.GetString("mnuChangeLN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change-part number.
        '''</summary>
        Public Shared ReadOnly Property mnuChangePN() As String
            Get
                Return ResourceManager.GetString("mnuChangePN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change-serial number.
        '''</summary>
        Public Shared ReadOnly Property mnuChangeSN() As String
            Get
                Return ResourceManager.GetString("mnuChangeSN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LDD Viewer.
        '''</summary>
        Public Shared ReadOnly Property mnuCLDDViewer() As String
            Get
                Return ResourceManager.GetString("mnuCLDDViewer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legacy.
        '''</summary>
        Public Shared ReadOnly Property mnuCLegacy() As String
            Get
                Return ResourceManager.GetString("mnuCLegacy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Public Shared ReadOnly Property mnuClose() As String
            Get
                Return ResourceManager.GetString("mnuClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data(&amp;D).
        '''</summary>
        Public Shared ReadOnly Property mnuData() As String
            Get
                Return ResourceManager.GetString("mnuData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Card.
        '''</summary>
        Public Shared ReadOnly Property mnuDeleteCard() As String
            Get
                Return ResourceManager.GetString("mnuDeleteCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit(&amp;E).
        '''</summary>
        Public Shared ReadOnly Property mnuEdit() As String
            Get
                Return ResourceManager.GetString("mnuEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit Application (&amp;X).
        '''</summary>
        Public Shared ReadOnly Property mnuExit() As String
            Get
                Return ResourceManager.GetString("mnuExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File(&amp;F).
        '''</summary>
        Public Shared ReadOnly Property mnuFile() As String
            Get
                Return ResourceManager.GetString("mnuFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change graph axis.
        '''</summary>
        Public Shared ReadOnly Property mnuGraph() As String
            Get
                Return ResourceManager.GetString("mnuGraph", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mark card.
        '''</summary>
        Public Shared ReadOnly Property mnuMark() As String
            Get
                Return ResourceManager.GetString("mnuMark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Public Shared ReadOnly Property mnuOpen() As String
            Get
                Return ResourceManager.GetString("mnuOpen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-calculation.
        '''</summary>
        Public Shared ReadOnly Property mnuReCalc() As String
            Get
                Return ResourceManager.GetString("mnuReCalc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Re-calculation Vf.
        '''</summary>
        Public Shared ReadOnly Property mnuReCalcVf() As String
            Get
                Return ResourceManager.GetString("mnuReCalcVf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Data.
        '''</summary>
        Public Shared ReadOnly Property mnuSave() As String
            Get
                Return ResourceManager.GetString("mnuSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Public Shared ReadOnly Property mnuSearch() As String
            Get
                Return ResourceManager.GetString("mnuSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMSR point.
        '''</summary>
        Public Shared ReadOnly Property mnuSmsrPoint() As String
            Get
                Return ResourceManager.GetString("mnuSmsrPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort.
        '''</summary>
        Public Shared ReadOnly Property mnuSort() As String
            Get
                Return ResourceManager.GetString("mnuSort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View(&amp;V).
        '''</summary>
        Public Shared ReadOnly Property mnuView() As String
            Get
                Return ResourceManager.GetString("mnuView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About Measurement.
        '''</summary>
        Public Shared ReadOnly Property mnuViewAbout() As String
            Get
                Return ResourceManager.GetString("mnuViewAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement result.
        '''</summary>
        Public Shared ReadOnly Property mnuViewChars() As String
            Get
                Return ResourceManager.GetString("mnuViewChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Public Shared ReadOnly Property mnuViewComment() As String
            Get
                Return ResourceManager.GetString("mnuViewComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View setting.
        '''</summary>
        Public Shared ReadOnly Property mnuViewSetup() As String
            Get
                Return ResourceManager.GetString("mnuViewSetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement condition.
        '''</summary>
        Public Shared ReadOnly Property mnuViewTerm() As String
            Get
                Return ResourceManager.GetString("mnuViewTerm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export view data.
        '''</summary>
        Public Shared ReadOnly Property mnuWrite() As String
            Get
                Return ResourceManager.GetString("mnuWrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export graph data.
        '''</summary>
        Public Shared ReadOnly Property mnuWriteNum() As String
            Get
                Return ResourceManager.GetString("mnuWriteNum", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
